// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proyecto2Back.Data;

#nullable disable

namespace proyecto2Back.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260509093108_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("proyecto2Back.Modelos.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("longtext");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("proyecto2Back.Modelos.WebApplication1.Models.Tareas", b =>
                {
                    b.Property<int>("IdTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTarea"));

                    b.Property<int>("AsignadoIdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("CreadorIdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaCulminacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaLimite")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdAsignado")
                        .HasColumnType("int");

                    b.Property<int>("IdCreador")
                        .HasColumnType("int");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdTarea");

                    b.HasIndex("AsignadoIdUsuario");

                    b.HasIndex("CreadorIdUsuario");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("proyecto2Back.Modelos.WebApplication1.Models.Tareas", b =>
                {
                    b.HasOne("proyecto2Back.Modelos.Usuario", "Asignado")
                        .WithMany()
                        .HasForeignKey("AsignadoIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("proyecto2Back.Modelos.Usuario", "Creador")
                        .WithMany()
                        .HasForeignKey("CreadorIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asignado");

                    b.Navigation("Creador");
                });
#pragma warning restore 612, 618
        }
    }
}
